name: 'Text to Emoji'
author: '@joshjohanning'
branding:
  icon: 'image'
  color: 'blue'
description: 'Returns an emoji as an output variable based on text input'
inputs:
  color:
    description: 'The color to return an emoji for'
    required: false
  food:
    description: 'The food to return an emoji for'
    required: false
  animal:
    description: 'The animal to return an emoji for'
    required: false
outputs:
  color-emoji:
    description: "The color emoji"
    value: ${{ steps.color-emoji-generator.outputs.color-emoji }}
  food-emoji:
    description: "The food emoji"
    value: ${{ steps.food-emoji-generator.outputs.food-emoji }}
  animal-emoji:
    description: "The animal emoji"
    value: ${{ steps.animal-emoji-generator.outputs.animal-emoji }}
runs:
  using: "composite"
  steps:
    - id: color-emoji-generator
      if: ${{ inputs.color != '' }}
      shell: bash
      run: |
        echo "processing color emoji..."
        echo "::debug::You entered ${{ inputs.color }}."
        
        case ${{ inputs.color }} in
          red) color=🌹 ;;
          orange) color=🎃 ;;
          yellow) color=🚖 ;;
          green) color=⛳️ ;;
          blue) color=👖 ;;
          indigo) color=🪁 ;;
          violet) color=🪻 ;;
          *)
            echo "You entered another color, ${{ inputs.color }}, so you get this emoji." 
            color=🎨 ;;
        esac
        
        echo "color-emoji=$(echo $color)" >> $GITHUB_OUTPUT
        
    - id: food-emoji-generator
      if: ${{ inputs.food != '' }}
      shell: bash
      run: |
        echo "processing food emoji..."
        echo "::debug::You entered ${{ inputs.food }}."
        
        case "${{ inputs.food }}" in
          "apple") food=🍎 ;;
          "apple2") food=🍏 ;;
          "avocado") food=🥑 ;;
          "bacon") food=🥓 ;;
          "bagel") food=🥯 ;;
          "banana") food=🍌 ;;
          "bean") food=🫘 ;;
          "beer") food=🍺 ;;
          "bell pepper") food=🫑 ;;
          "birthday cake") food=🎂 ;;
          "blueberry") food=🫐 ;;
          "bread") food=🍞 ;;
          "bread2") food=🥖 ;;
          "broccoli") food=🥦 ;;
          "burger") food=🍔 ;;
          "burrito") food=🌯 ;;
          "butter") food=🧈 ;;
          "cake") food=🍰 ;;
          "candy") food=🍬 ;;
          "carrot") food=🥕 ;;
          "cheese") food=🧀 ;;
          "cherry") food=🍒 ;;
          "chestnut") food=🌰 ;;
          "chicken") food=🍗 ;;
          "chili pepper") food=🌶 ;;
          "chinese") food=🥡 ;;
          "chocolate") food=🍫 ;;
          "cocktail") food=🍸 ;;
          "coconut") food=🥥 ;;
          "coffee") food=☕️ ;;
          "cookie") food=🍪 ;;
          "corn") food=🌽 ;;
          "croissant") food=🥐 ;;
          "cucumber") food=🥒 ;;
          "cupcake") food=🧁 ;;
          "curry") food=🍛 ;;
          "custard") food=🍮 ;;
          "donut") food=🍩 ;;
          "egg") food=🍳 ;;
          "egg2") food=🥚 ;;
          "eggplant") food=🍆 ;;
          "falafel") food=🧆 ;;
          "fish") food=🍣 ;;
          "fondue") food=🫕 ;;
          "fortune cookie") food=🥠 ;;
          "french fry") food=🍟 ;;
          "fry") food=🍟 ;;
          "garlic") food=🧄 ;;
          "grape") food=🍇 ;;
          "honey") food=🍯 ;;
          "hot dog") food=🌭 ;;
          "ice cream") food=🍦 ;;
          "kiwi") food=🥝 ;;
          "lemon") food=🍋 ;;
          "lettuce") food=🥬 ;;
          "lobster") food=🦞 ;;
          "lollipop") food=🍭 ;;
          "mango") food=🥭 ;;
          "meat") food=🍖 ;;
          "melon") food=🍈 ;;
          "milk") food=🥛 ;;
          "mooncake") food=🥮 ;;
          "mushroom") food=🍄 ;;
          "noodle") food=🍜 ;;
          "oden") food=🍢 ;;
          "olive") food=🫒 ;;
          "onion") food=🧅 ;;
          "orange") food=🍊 ;;
          "oyster") food=🦪 ;;
          "pad thai") food=🍲 ;;
          "pancake") food=🥞 ;;
          "pea pod") food=🫛 ;;
          "pea") food=🫛 ;;
          "peach") food=🍑 ;;
          "peanut") food=🥜 ;;
          "pear") food=🍐 ;;
          "pepper") food=🫑 ;;
          "pepper2") food=🌶 ;;
          "pie") food=🥧 ;;
          "pineapple") food=🍍 ;;
          "pita") food=🥙 ;;
          "pizza") food=🍕 ;;
          "popcorn") food=🍿 ;;
          "potato") food=🥔 ;;
          "potato2") food=🍠 ;;
          "pretzel") food=🥨 ;;
          "ramen") food=🍜 ;;
          "rice") food=🍚 ;;
          "salad") food=🥗 ;;
          "sandwich") food=🥪 ;;
          "shaved ice") food=🍧 ;;
          "shrimp") food=🍤 ;;
          "shrimp2") food=🦐 ;;
          "soda") food=🥤 ;;
          "soup") food=🍲 ;;
          "spaghetti") food=🍝 ;;
          "steak") food=🥩 ;;
          "strawberry") food=🍓 ;;
          "sundae") food=🍨 ;;
          "sushi") food=🍣 ;;
          "sweet potato") food=🍠 ;;
          "taco") food=🌮 ;;
          "tamale") food=🫔 ;;
          "tea") food=🍵 ;;
          "tomato") food=🍅 ;;
          "waffle") food=🧇 ;;
          "watermelon") food=🍉 ;;
          "wine") food=🍷 ;;
          "wonton") food=🥟 ;;
          *)
            echo "You entered another food, ${{ inputs.food }}, so you get this emoji."
            food=🍽️ ;;
        esac
        
        echo "food-emoji=$(echo $food)" >> $GITHUB_OUTPUT

    - id: animal-emoji-generator
      if: ${{ inputs.animal != '' }}
      shell: bash
      run: |
        echo "processing animal emoji..."
        echo "::debug::You entered ${{ inputs.animal }}."
        
        case ${{ inputs.animal }} in
          alligator) animal=🐊 ;;
          alpaca) animal=🦙 ;;
          ant) animal=🐜 ;;
          badger) animal=🦡 ;;
          bat) animal=🦇 ;;
          bear) animal=🐻 ;;
          bee) animal=🐝 ;;
          beetle) animal=🪲 ;;
          bird) animal=🕊️ ;;
          bison) animal=🦬 ;;
          blowfish) animal=🐡 ;;
          boar) animal=🐗 ;;
          brontosaurus) animal=🦕 ;;
          buffalo) animal=🐃 ;;
          bunny) animal=🐰 ;;
          butterfly) animal=🦋 ;;
          camel) animal=🐫 ;;
          cat) animal=🐱 ;;
          cat2) animal=🐈 ;;
          caterpillar) animal=🐛 ;;
          chic) animal=🐣 ;;
          chic2) animal=🐤 ;;
          chicken) animal=🐔 ;;
          chicken2) animal=🐓 ;;
          chipmunk) animal=🐿️ ;;
          cockroach) animal=🪳 ;;
          cow) animal=🐮 ;;
          cow2) animal=🐄 ;;
          crab) animal=🦀 ;;
          cricket) animal=🦗 ;;
          crocodile) animal=🐊 ;;
          crow) animal=🐦‍⬛ ;;
          deer) animal=🦌 ;;
          dinosaur) animal=🦖 ;;
          dinosaur2) animal=🦕 ;;
          dodo) animal=🦤 ;;
          dog) animal=🐶 ;;
          dog2) animal=🐕 ;;
          dolphin) animal=🐬 ;;
          donkey) animal=🫏 ;;
          dove) animal=🕊️ ;;
          dragon) animal=🐉 ;;
          duck) animal=🦆 ;;
          eagle) animal=🦅 ;;
          elephant) animal=🐘 ;;
          elk) animal=🫎 ;;
          fish) animal=🐟 ;;
          fish2) animal=🐠 ;;
          fish3) animal=🎣 ;;
          flamingo) animal=🦩 ;;
          fly) animal=🪰 ;;
          fox) animal=🦊 ;;
          frog) animal=🐸 ;;
          giraffe) animal=🦒 ;;
          goat) animal=🐐 ;;
          goose) animal=🪿 ;;
          gorilla) animal=🦍 ;;
          hedgehog) animal=🦔 ;;
          hippo) animal=🦛 ;;
          horse) animal=🐴 ;;
          horse2) animal=🐎 ;;
          kangaroo) animal=🦘 ;;
          koala) animal=🐨 ;;
          ladybug) animal=🐞 ;;
          lion) animal=🦁 ;;
          lizard) animal=🦎 ;;
          llama) animal=🦙 ;;
          lobster) animal=🦞 ;;
          monkey) animal=🐵 ;;
          monkey2) animal=🐒 ;;
          moose) animal=🫎 ;;
          mosquito) animal=🦟 ;;
          mouse) animal=🐭 ;;
          mouse2) animal=🐁 ;;
          octopus) animal=🐙 ;;
          owl) animal=🦉 ;;
          ox) animal=🐂 ;;
          panda) animal=🐼 ;;
          parrot) animal=🦜 ;;
          peacock) animal=🦚 ;;
          penguin) animal=🐧 ;;
          pig) animal=🐷 ;;
          pig2) animal=🐖 ;;
          poodle) animal=🐩 ;;
          rabbit) animal=🐇 ;;
          raccoon) animal=🦝 ;;
          ram) animal=🐑 ;;
          rat) animal=🐀 ;;
          rhino) animal=🦏 ;;
          sheep) animal=🐑 ;;
          shrimp) animal=🦐 ;;
          snail) animal=🐌 ;;
          snake) animal=🐍 ;;
          spider) animal=🕷️ ;;
          squid) animal=🦑 ;;
          squirrel) animal=🐿️ ;;
          swan) animal=🦢 ;;
          teddy) animal=🧸 ;;
          tiger) animal=🐯 ;;
          trex) animal=🦖 ;;
          turkey) animal=🦃 ;;
          turtle) animal=🐢 ;;
          unicorn) animal=🦄 ;;
          whale) animal=🐳 ;;
          wolf) animal=🐺 ;;
          zebra) animal=🦓 ;;
          *) 
            echo "You entered another animal, ${{ inputs.animal }}, so you get this emoji."
            animal=🎨 ;;
        esac
        
        echo "animal-emoji=$(echo $animal)" >> $GITHUB_OUTPUT
